CREATE TABLE stock_daily_prices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id BIGINT NOT NULL,
    base_date DATE NOT NULL,
    close_price NUMERIC(19, 2) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_stock_daily_prices_asset_date UNIQUE (asset_id, base_date),
    CONSTRAINT fk_stock_daily_prices_asset FOREIGN KEY (asset_id) REFERENCES assets (id),
    CONSTRAINT ck_stock_daily_prices_close_price_positive CHECK (close_price > 0)
);

CREATE INDEX idx_stock_daily_prices_asset_date
    ON stock_daily_prices (asset_id, base_date DESC);
