CREATE TABLE portfolios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_portfolios_member UNIQUE (member_id),
    CONSTRAINT fk_portfolios_member FOREIGN KEY (member_id) REFERENCES members (id)
);

CREATE TABLE portfolio_holdings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portfolio_id BIGINT NOT NULL,
    asset_id BIGINT NOT NULL,
    quantity BIGINT NOT NULL,
    average_purchase_price NUMERIC(19, 2) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_portfolio_holdings_portfolio_asset UNIQUE (portfolio_id, asset_id),
    CONSTRAINT fk_portfolio_holdings_portfolio FOREIGN KEY (portfolio_id) REFERENCES portfolios (id) ON DELETE CASCADE,
    CONSTRAINT fk_portfolio_holdings_asset FOREIGN KEY (asset_id) REFERENCES assets (id),
    CONSTRAINT ck_portfolio_holdings_quantity_positive CHECK (quantity > 0),
    CONSTRAINT ck_portfolio_holdings_average_price_positive CHECK (average_purchase_price > 0)
);

CREATE TABLE portfolio_holding_histories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portfolio_id BIGINT NOT NULL,
    asset_id BIGINT NOT NULL,
    change_type VARCHAR(20) NOT NULL,
    quantity BIGINT NOT NULL,
    average_purchase_price NUMERIC(19, 2) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_portfolio_holding_histories_portfolio FOREIGN KEY (portfolio_id) REFERENCES portfolios (id) ON DELETE CASCADE,
    CONSTRAINT fk_portfolio_holding_histories_asset FOREIGN KEY (asset_id) REFERENCES assets (id),
    CONSTRAINT ck_portfolio_holding_histories_quantity_non_negative CHECK (quantity >= 0),
    CONSTRAINT ck_portfolio_holding_histories_average_price_non_negative CHECK (average_purchase_price >= 0)
);

CREATE INDEX idx_portfolio_holding_histories_portfolio_created
    ON portfolio_holding_histories (portfolio_id, created_at DESC);

CREATE TABLE portfolio_daily_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portfolio_id BIGINT NOT NULL,
    base_date DATE NOT NULL,
    total_purchase_amount NUMERIC(19, 2) NOT NULL,
    total_evaluation_amount NUMERIC(19, 2) NOT NULL,
    total_profit_loss NUMERIC(19, 2) NOT NULL,
    total_return_rate NUMERIC(10, 2) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_portfolio_daily_snapshots_portfolio_date UNIQUE (portfolio_id, base_date),
    CONSTRAINT fk_portfolio_daily_snapshots_portfolio FOREIGN KEY (portfolio_id) REFERENCES portfolios (id) ON DELETE CASCADE
);

CREATE INDEX idx_portfolio_daily_snapshots_portfolio_date
    ON portfolio_daily_snapshots (portfolio_id, base_date DESC);
