CREATE TABLE stock_related_contents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id BIGINT NOT NULL,
    source_type VARCHAR(30) NOT NULL,
    title VARCHAR(255) NOT NULL,
    url TEXT NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_stock_related_contents_asset_url UNIQUE (asset_id, url),
    CONSTRAINT fk_stock_related_contents_asset FOREIGN KEY (asset_id) REFERENCES assets (id)
);

CREATE INDEX idx_stock_related_contents_asset_created
    ON stock_related_contents (asset_id, created_at DESC, id DESC);
