CREATE TABLE members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider VARCHAR(20) NOT NULL,
    provider_id VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    nickname VARCHAR(20) NOT NULL,
    profile_image_url VARCHAR(500),
    role VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    withdrawn_at TIMESTAMP(6) WITH TIME ZONE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_members_provider_provider_id UNIQUE (provider, provider_id),
    CONSTRAINT uk_members_nickname UNIQUE (nickname)
);

CREATE TABLE assets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    category VARCHAR(255) NOT NULL,
    asset_code VARCHAR(50) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_assets_category_asset_code UNIQUE (category, asset_code)
);

CREATE TABLE news (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    description TEXT,
    image_url TEXT,
    source VARCHAR(255) NOT NULL,
    external_id VARCHAR(255) NOT NULL,
    source_url TEXT NOT NULL,
    category VARCHAR(255) NOT NULL,
    published_at TIMESTAMP(6) WITH TIME ZONE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_news_source_external_id UNIQUE (source, external_id)
);

CREATE TABLE refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL,
    token_hash VARCHAR(64) NOT NULL,
    expires_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_refresh_tokens_token_hash UNIQUE (token_hash),
    CONSTRAINT fk_refresh_tokens_member FOREIGN KEY (member_id) REFERENCES members (id)
);

CREATE TABLE bookmarks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id BIGINT NOT NULL,
    member_id BIGINT NOT NULL,
    CONSTRAINT uk_bookmarks_member_asset UNIQUE (member_id, asset_id),
    CONSTRAINT fk_bookmarks_asset FOREIGN KEY (asset_id) REFERENCES assets (id),
    CONSTRAINT fk_bookmarks_member FOREIGN KEY (member_id) REFERENCES members (id)
);

CREATE TABLE asset_ranking_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id BIGINT NOT NULL,
    ranking INTEGER NOT NULL,
    ranked_date DATE NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_asset_ranking_history_ranked_date_ranking UNIQUE (ranked_date, ranking),
    CONSTRAINT fk_asset_ranking_history_asset FOREIGN KEY (asset_id) REFERENCES assets (id)
);

CREATE TABLE news_market_analysis (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    news_id BIGINT NOT NULL,
    cause TEXT NOT NULL,
    importance TEXT NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_news_market_analysis_news UNIQUE (news_id),
    CONSTRAINT fk_news_market_analysis_news FOREIGN KEY (news_id) REFERENCES news (id)
);

CREATE TABLE news_market_analysis_assets (
    news_market_analysis_id BIGINT NOT NULL,
    sort_order INTEGER NOT NULL,
    category VARCHAR(255) NOT NULL,
    direction VARCHAR(255) NOT NULL,
    impact_level VARCHAR(255) NOT NULL,
    reason TEXT NOT NULL,
    CONSTRAINT fk_news_market_analysis_assets_analysis
        FOREIGN KEY (news_market_analysis_id) REFERENCES news_market_analysis (id)
);

CREATE TABLE news_market_analysis_scenarios (
    news_market_analysis_id BIGINT NOT NULL,
    sort_order INTEGER NOT NULL,
    time_horizon VARCHAR(255) NOT NULL,
    prediction TEXT NOT NULL,
    probability INTEGER NOT NULL,
    reason TEXT NOT NULL,
    CONSTRAINT fk_news_market_analysis_scenarios_analysis
        FOREIGN KEY (news_market_analysis_id) REFERENCES news_market_analysis (id)
);

CREATE TABLE portfolio_asset_impact (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    news_id BIGINT NOT NULL,
    asset_id BIGINT NOT NULL,
    bookmark_id BIGINT NOT NULL,
    direction VARCHAR(255) NOT NULL,
    impact_level VARCHAR(255) NOT NULL,
    expected_reaction TEXT NOT NULL,
    reason TEXT NOT NULL,
    sort_order INTEGER NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_portfolio_asset_impact_news_bookmark UNIQUE (news_id, bookmark_id),
    CONSTRAINT fk_portfolio_asset_impact_news FOREIGN KEY (news_id) REFERENCES news (id),
    CONSTRAINT fk_portfolio_asset_impact_asset FOREIGN KEY (asset_id) REFERENCES assets (id),
    CONSTRAINT fk_portfolio_asset_impact_bookmark FOREIGN KEY (bookmark_id) REFERENCES bookmarks (id)
);

CREATE TABLE news_keyword (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    news_id BIGINT NOT NULL,
    category VARCHAR(255) NOT NULL,
    keyword VARCHAR(255) NOT NULL,
    point1 TEXT NOT NULL,
    point2 TEXT NOT NULL,
    point3 TEXT NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_news_keyword_news FOREIGN KEY (news_id) REFERENCES news (id)
);
