CREATE TABLE investment_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type VARCHAR(30) NOT NULL,
    title VARCHAR(100) NOT NULL,
    announced_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    previous_value NUMERIC(19, 4),
    actual_value NUMERIC(19, 4),
    value_unit VARCHAR(20) NOT NULL,
    source_name VARCHAR(50) NOT NULL,
    source_url VARCHAR(500) NOT NULL,
    source_key VARCHAR(100) NOT NULL,
    related_asset_code VARCHAR(50),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_investment_events_source_key UNIQUE (source_key)
);

CREATE INDEX idx_investment_events_announced_at
    ON investment_events (announced_at);

CREATE INDEX idx_investment_events_type_announced_at
    ON investment_events (event_type, announced_at);
