CREATE TABLE romi_progress (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL,
    item_key VARCHAR(100) NOT NULL,
    item_type VARCHAR(20) NOT NULL,
    completed BOOLEAN NOT NULL DEFAULT FALSE,
    bookmarked BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_romi_progress_member_item UNIQUE (member_id, item_key),
    CONSTRAINT fk_romi_progress_member FOREIGN KEY (member_id) REFERENCES members (id) ON DELETE CASCADE
);

CREATE TABLE romi_weekly_check_ins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL,
    week_start DATE NOT NULL,
    target_savings NUMERIC(19, 2) NOT NULL,
    target_investment NUMERIC(19, 2) NOT NULL,
    target_debt_payment NUMERIC(19, 2) NOT NULL,
    actual_savings NUMERIC(19, 2) NOT NULL,
    actual_investment NUMERIC(19, 2) NOT NULL,
    actual_debt_payment NUMERIC(19, 2) NOT NULL,
    note VARCHAR(200),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_romi_check_ins_member_week UNIQUE (member_id, week_start),
    CONSTRAINT fk_romi_check_ins_member FOREIGN KEY (member_id) REFERENCES members (id) ON DELETE CASCADE,
    CONSTRAINT ck_romi_check_ins_non_negative CHECK (
        target_savings >= 0 AND target_investment >= 0 AND target_debt_payment >= 0
        AND actual_savings >= 0 AND actual_investment >= 0 AND actual_debt_payment >= 0
    )
);

CREATE INDEX idx_romi_check_ins_member_week
    ON romi_weekly_check_ins (member_id, week_start DESC);

CREATE TABLE romi_mock_trades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL,
    asset_id BIGINT NOT NULL,
    trade_type VARCHAR(10) NOT NULL,
    quantity BIGINT NOT NULL,
    price NUMERIC(19, 2) NOT NULL,
    reason VARCHAR(200),
    traded_on DATE NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_romi_mock_trades_member FOREIGN KEY (member_id) REFERENCES members (id) ON DELETE CASCADE,
    CONSTRAINT fk_romi_mock_trades_asset FOREIGN KEY (asset_id) REFERENCES assets (id),
    CONSTRAINT ck_romi_mock_trades_quantity_positive CHECK (quantity > 0),
    CONSTRAINT ck_romi_mock_trades_price_positive CHECK (price > 0)
);

CREATE INDEX idx_romi_mock_trades_member_date
    ON romi_mock_trades (member_id, traded_on DESC, id DESC);
