CREATE TABLE public_investor_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL,
    public_id VARCHAR(36) NOT NULL,
    display_name VARCHAR(20) NOT NULL,
    bio VARCHAR(120) NOT NULL DEFAULT '',
    experience_level VARCHAR(20) NOT NULL,
    risk_profile VARCHAR(20) NOT NULL,
    profile_public BOOLEAN NOT NULL DEFAULT FALSE,
    league_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    allocation_public BOOLEAN NOT NULL DEFAULT TRUE,
    premium_detail_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    league_enabled_at TIMESTAMP(6) WITH TIME ZONE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_public_investor_profiles_member UNIQUE (member_id),
    CONSTRAINT uk_public_investor_profiles_public_id UNIQUE (public_id),
    CONSTRAINT uk_public_investor_profiles_display_name UNIQUE (display_name),
    CONSTRAINT fk_public_investor_profiles_member FOREIGN KEY (member_id) REFERENCES members (id) ON DELETE CASCADE
);

CREATE TABLE portfolio_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portfolio_id BIGINT NOT NULL,
    asset_id BIGINT NOT NULL,
    request_key VARCHAR(80) NOT NULL,
    transaction_type VARCHAR(10) NOT NULL,
    quantity BIGINT NOT NULL,
    unit_price NUMERIC(19, 2) NOT NULL,
    fee NUMERIC(19, 2) NOT NULL DEFAULT 0,
    traded_on DATE NOT NULL,
    decision_reason VARCHAR(500) NOT NULL,
    expected_holding_period VARCHAR(30) NOT NULL,
    expected_change VARCHAR(300) NOT NULL,
    invalidation_condition VARCHAR(300) NOT NULL,
    maximum_acceptable_loss_rate NUMERIC(5, 2) NOT NULL,
    written_after_trade BOOLEAN NOT NULL DEFAULT FALSE,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_portfolio_transactions_request UNIQUE (portfolio_id, request_key),
    CONSTRAINT fk_portfolio_transactions_portfolio FOREIGN KEY (portfolio_id) REFERENCES portfolios (id) ON DELETE CASCADE,
    CONSTRAINT fk_portfolio_transactions_asset FOREIGN KEY (asset_id) REFERENCES assets (id),
    CONSTRAINT ck_portfolio_transactions_quantity_positive CHECK (quantity > 0),
    CONSTRAINT ck_portfolio_transactions_price_positive CHECK (unit_price > 0),
    CONSTRAINT ck_portfolio_transactions_fee_non_negative CHECK (fee >= 0),
    CONSTRAINT ck_portfolio_transactions_loss_rate CHECK (maximum_acceptable_loss_rate BETWEEN 0 AND 100)
);

CREATE INDEX idx_portfolio_transactions_portfolio_date
    ON portfolio_transactions (portfolio_id, traded_on DESC, id DESC);

CREATE TABLE investment_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id BIGINT NOT NULL,
    actual_result VARCHAR(500) NOT NULL,
    difference_from_expectation VARCHAR(500) NOT NULL,
    next_action VARCHAR(500) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_investment_reviews_transaction FOREIGN KEY (transaction_id) REFERENCES portfolio_transactions (id) ON DELETE CASCADE
);

CREATE TABLE portfolio_daily_returns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portfolio_id BIGINT NOT NULL,
    base_date DATE NOT NULL,
    daily_return_rate NUMERIC(10, 4),
    starting_evaluation_amount NUMERIC(19, 2),
    ending_evaluation_amount NUMERIC(19, 2),
    max_holding_weight NUMERIC(10, 2),
    eligible BOOLEAN NOT NULL,
    ineligible_reason VARCHAR(40),
    calculation_version INTEGER NOT NULL DEFAULT 1,
    calculated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_portfolio_daily_returns_date_version UNIQUE (portfolio_id, base_date, calculation_version),
    CONSTRAINT fk_portfolio_daily_returns_portfolio FOREIGN KEY (portfolio_id) REFERENCES portfolios (id) ON DELETE CASCADE
);

CREATE INDEX idx_portfolio_daily_returns_date
    ON portfolio_daily_returns (base_date DESC, eligible);

CREATE TABLE investor_follows (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    follower_member_id BIGINT NOT NULL,
    profile_id BIGINT NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_investor_follows_follower_profile UNIQUE (follower_member_id, profile_id),
    CONSTRAINT fk_investor_follows_member FOREIGN KEY (follower_member_id) REFERENCES members (id) ON DELETE CASCADE,
    CONSTRAINT fk_investor_follows_profile FOREIGN KEY (profile_id) REFERENCES public_investor_profiles (id) ON DELETE CASCADE
);

CREATE TABLE subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL,
    product_code VARCHAR(40) NOT NULL,
    status VARCHAR(20) NOT NULL,
    access_until TIMESTAMP(6) WITH TIME ZONE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_subscriptions_member_product UNIQUE (member_id, product_code),
    CONSTRAINT fk_subscriptions_member FOREIGN KEY (member_id) REFERENCES members (id) ON DELETE CASCADE
);
