-- 원본 데이터는 변경하지 않는다. 기존 리그 기록의 FK만 독립 사본으로 전환한다.
CREATE TABLE shared_portfolios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL UNIQUE REFERENCES members(id) ON DELETE CASCADE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);
CREATE TABLE shared_holdings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portfolio_id BIGINT NOT NULL REFERENCES shared_portfolios(id) ON DELETE CASCADE,
    asset_id BIGINT NOT NULL REFERENCES assets(id),
    quantity BIGINT NOT NULL CHECK (quantity BETWEEN 1 AND 1000000000),
    average_purchase_price NUMERIC(19,2) NOT NULL CHECK (average_purchase_price > 0),
    hidden BOOLEAN NOT NULL DEFAULT FALSE,
    reason VARCHAR(500) NOT NULL DEFAULT '',
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    UNIQUE(portfolio_id, asset_id)
);
CREATE TABLE shared_holding_histories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portfolio_id BIGINT NOT NULL REFERENCES shared_portfolios(id) ON DELETE CASCADE,
    asset_id BIGINT NOT NULL REFERENCES assets(id),
    change_type VARCHAR(20) NOT NULL,
    quantity BIGINT NOT NULL,
    average_purchase_price NUMERIC(19,2) NOT NULL,
    hidden BOOLEAN NOT NULL DEFAULT FALSE,
    reason VARCHAR(500) NOT NULL DEFAULT '',
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);
CREATE INDEX idx_shared_history_close ON shared_holding_histories(portfolio_id, created_at, id);

INSERT INTO shared_portfolios(id, member_id, created_at, updated_at)
SELECT p.id, p.member_id, p.created_at, p.updated_at FROM portfolios p
WHERE EXISTS (SELECT 1 FROM public_investor_profiles pr WHERE pr.member_id = p.member_id)
   OR EXISTS (SELECT 1 FROM portfolio_transactions t WHERE t.portfolio_id = p.id)
   OR EXISTS (SELECT 1 FROM portfolio_daily_returns r WHERE r.portfolio_id = p.id);
SELECT setval(pg_get_serial_sequence('shared_portfolios', 'id'),
              COALESCE((SELECT MAX(id) FROM shared_portfolios), 1),
              EXISTS(SELECT 1 FROM shared_portfolios));

INSERT INTO shared_holdings(portfolio_id, asset_id, quantity, average_purchase_price, created_at, updated_at)
SELECT h.portfolio_id, h.asset_id, h.quantity, h.average_purchase_price, h.created_at, h.updated_at
FROM portfolio_holdings h JOIN shared_portfolios s ON s.id = h.portfolio_id;
INSERT INTO shared_holding_histories(portfolio_id, asset_id, change_type, quantity, average_purchase_price, created_at, updated_at)
SELECT h.portfolio_id, h.asset_id, h.change_type, h.quantity, h.average_purchase_price, h.created_at, h.updated_at
FROM portfolio_holding_histories h JOIN shared_portfolios s ON s.id = h.portfolio_id
ORDER BY h.created_at, h.id;

ALTER TABLE portfolio_transactions DROP CONSTRAINT fk_portfolio_transactions_portfolio;
ALTER TABLE portfolio_transactions ADD CONSTRAINT fk_transactions_shared FOREIGN KEY(portfolio_id) REFERENCES shared_portfolios(id) ON DELETE CASCADE;
ALTER TABLE portfolio_daily_returns DROP CONSTRAINT fk_portfolio_daily_returns_portfolio;
ALTER TABLE portfolio_daily_returns ADD CONSTRAINT fk_returns_shared FOREIGN KEY(portfolio_id) REFERENCES shared_portfolios(id) ON DELETE CASCADE;
