CREATE TABLE romi_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL REFERENCES members(id) ON DELETE CASCADE,
    plan_key VARCHAR(80) NOT NULL,
    content JSONB NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    UNIQUE(member_id, plan_key)
);
CREATE INDEX idx_romi_plans_member_date ON romi_plans(member_id, created_at DESC);
