-- 이미 적용된 V20~V24의 체크섬과 데이터를 유지하고 이름만 변경한다.
ALTER TABLE romi_progress RENAME TO learning_progress;
ALTER TABLE learning_progress RENAME CONSTRAINT romi_progress_pkey TO learning_progress_pkey;
ALTER TABLE learning_progress RENAME CONSTRAINT uk_romi_progress_member_item TO uk_learning_progress_member_item;
ALTER TABLE learning_progress RENAME CONSTRAINT fk_romi_progress_member TO fk_learning_progress_member;
ALTER SEQUENCE romi_progress_id_seq RENAME TO learning_progress_id_seq;

ALTER TABLE romi_weekly_check_ins RENAME TO weekly_check_ins;
ALTER TABLE weekly_check_ins RENAME CONSTRAINT romi_weekly_check_ins_pkey TO weekly_check_ins_pkey;
ALTER TABLE weekly_check_ins RENAME CONSTRAINT uk_romi_check_ins_member_week TO uk_weekly_check_ins_member_week;
ALTER TABLE weekly_check_ins RENAME CONSTRAINT fk_romi_check_ins_member TO fk_weekly_check_ins_member;
ALTER TABLE weekly_check_ins RENAME CONSTRAINT ck_romi_check_ins_non_negative TO ck_weekly_check_ins_non_negative;
ALTER INDEX idx_romi_check_ins_member_week RENAME TO idx_weekly_check_ins_member_week;
ALTER SEQUENCE romi_weekly_check_ins_id_seq RENAME TO weekly_check_ins_id_seq;

ALTER TABLE romi_mock_trades RENAME TO simulated_trades;
ALTER TABLE simulated_trades RENAME CONSTRAINT romi_mock_trades_pkey TO simulated_trades_pkey;
ALTER TABLE simulated_trades RENAME CONSTRAINT fk_romi_mock_trades_member TO fk_simulated_trades_member;
ALTER TABLE simulated_trades RENAME CONSTRAINT fk_romi_mock_trades_asset TO fk_simulated_trades_asset;
ALTER TABLE simulated_trades RENAME CONSTRAINT ck_romi_mock_trades_quantity_positive TO ck_simulated_trades_quantity_positive;
ALTER TABLE simulated_trades RENAME CONSTRAINT ck_romi_mock_trades_price_positive TO ck_simulated_trades_price_positive;
ALTER INDEX idx_romi_mock_trades_member_date RENAME TO idx_simulated_trades_member_date;
ALTER SEQUENCE romi_mock_trades_id_seq RENAME TO simulated_trades_id_seq;

ALTER TABLE romi_plans RENAME TO financial_plans;
ALTER TABLE financial_plans RENAME CONSTRAINT romi_plans_pkey TO financial_plans_pkey;
ALTER TABLE financial_plans RENAME CONSTRAINT romi_plans_member_id_fkey TO financial_plans_member_id_fkey;
ALTER TABLE financial_plans RENAME CONSTRAINT romi_plans_member_id_plan_key_key TO financial_plans_member_id_plan_key_key;
ALTER INDEX idx_romi_plans_member_date RENAME TO idx_financial_plans_member_date;
ALTER SEQUENCE romi_plans_id_seq RENAME TO financial_plans_id_seq;

ALTER TABLE shared_portfolios_romi RENAME TO shared_portfolios;
ALTER TABLE shared_portfolios RENAME CONSTRAINT shared_portfolios_romi_pkey TO shared_portfolios_pkey;
ALTER TABLE shared_portfolios RENAME CONSTRAINT shared_portfolios_romi_member_id_key TO shared_portfolios_member_id_key;
ALTER TABLE shared_portfolios RENAME CONSTRAINT shared_portfolios_romi_member_id_fkey TO shared_portfolios_member_id_fkey;
ALTER SEQUENCE shared_portfolios_romi_id_seq RENAME TO shared_portfolios_id_seq;

ALTER TABLE shared_holdings_romi RENAME TO shared_holdings;
ALTER TABLE shared_holdings RENAME CONSTRAINT shared_holdings_romi_pkey TO shared_holdings_pkey;
ALTER TABLE shared_holdings RENAME CONSTRAINT shared_holdings_romi_portfolio_id_fkey TO shared_holdings_portfolio_id_fkey;
ALTER TABLE shared_holdings RENAME CONSTRAINT shared_holdings_romi_asset_id_fkey TO shared_holdings_asset_id_fkey;
ALTER TABLE shared_holdings RENAME CONSTRAINT shared_holdings_romi_quantity_check TO shared_holdings_quantity_check;
ALTER TABLE shared_holdings RENAME CONSTRAINT shared_holdings_romi_average_purchase_price_check TO shared_holdings_average_purchase_price_check;
ALTER TABLE shared_holdings RENAME CONSTRAINT shared_holdings_romi_portfolio_id_asset_id_key TO shared_holdings_portfolio_id_asset_id_key;
ALTER SEQUENCE shared_holdings_romi_id_seq RENAME TO shared_holdings_id_seq;

ALTER TABLE shared_holding_histories_romi RENAME TO shared_holding_histories;
ALTER TABLE shared_holding_histories RENAME CONSTRAINT shared_holding_histories_romi_pkey TO shared_holding_histories_pkey;
ALTER TABLE shared_holding_histories RENAME CONSTRAINT shared_holding_histories_romi_portfolio_id_fkey TO shared_holding_histories_portfolio_id_fkey;
ALTER TABLE shared_holding_histories RENAME CONSTRAINT shared_holding_histories_romi_asset_id_fkey TO shared_holding_histories_asset_id_fkey;
ALTER INDEX idx_shared_history_romi_close RENAME TO idx_shared_history_close;
ALTER SEQUENCE shared_holding_histories_romi_id_seq RENAME TO shared_holding_histories_id_seq;

ALTER TABLE portfolio_transactions RENAME CONSTRAINT fk_transactions_shared_romi TO fk_transactions_shared;
ALTER TABLE portfolio_daily_returns RENAME CONSTRAINT fk_returns_shared_romi TO fk_returns_shared;
