global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: daynomy

rule_files:
  - /etc/prometheus/rules/*.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090
        labels:
          environment: monitoring
          service: prometheus

  - job_name: alertmanager
    static_configs:
      - targets:
          - alertmanager:9093
        labels:
          environment: monitoring
          service: alertmanager

  - job_name: blackbox-exporter
    static_configs:
      - targets:
          - blackbox-exporter:9115
        labels:
          environment: monitoring
          service: blackbox-exporter

  - job_name: blackbox-http
    metrics_path: /probe
    params:
      module:
        - http_2xx
    static_configs:
      - targets:
          - https://dev.daynomy.com/
          - https://dev.daynomy.com/api/news
        labels:
          environment: dev
          service: public-endpoint
      - targets:
          - https://daynomy.com/
          - https://daynomy.com/api/news
        labels:
          environment: prod
          service: public-endpoint
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
