spring:
  config:
    activate:
      on-profile: prod

news:
  generation:
    economy:
      enabled: true

stock:
  price:
    sync:
      enabled: true

portfolio:
  snapshot:
    enabled: true

league:
  calculation:
    enabled: ${LEAGUE_CALCULATION_ENABLED:true}

management:
  metrics:
    tags:
      environment: prod
